import type { Service } from '../types';

export const services: Service[] = [
  {
    id: 'classic-manicure',
    category: 'manicure',
    name: 'Classic Manicure',
    duration: 30,
    price: 500,
    description: 'Nail shaping, cuticle care, hand massage, and polish of your choice.',
    popular: true,
  },
  {
    id: 'spa-manicure',
    category: 'manicure',
    name: 'Spa Manicure',
    duration: 45,
    price: 800,
    description: 'Luxurious soak, exfoliating scrub, mask, hot towel wrap, and extended massage.',
  },
  {
    id: 'gel-manicure',
    category: 'gel-acrylic',
    name: 'Gel Manicure',
    duration: 45,
    price: 800,
    description: 'Long-lasting gel polish with high-shine finish. No chips for up to 3 weeks.',
    popular: true,
  },
  {
    id: 'acrylic-full-set',
    category: 'gel-acrylic',
    name: 'Acrylic Full Set',
    duration: 90,
    price: 1250,
    description: 'Sculpted acrylic extensions with your choice of shape, length, and color.',
  },
  {
    id: 'acrylic-fill',
    category: 'gel-acrylic',
    name: 'Acrylic Fill',
    duration: 60,
    price: 800,
    description: 'Maintain your acrylic set with a fill and fresh polish.',
  },
  {
    id: 'classic-pedicure',
    category: 'pedicure',
    name: 'Classic Pedicure',
    duration: 45,
    price: 700,
    description: 'Soothing foot soak, nail care, callus smoothing, and polish.',
    popular: true,
  },
  {
    id: 'spa-pedicure',
    category: 'pedicure',
    name: 'Spa Pedicure',
    duration: 60,
    price: 1000,
    description: 'Ultimate relaxation with extended massage, mask, and hot stone treatment.',
  },
  {
    id: 'gel-pedicure',
    category: 'pedicure',
    name: 'Gel Pedicure',
    duration: 60,
    price: 1000,
    description: 'Long-lasting gel polish on toes. Perfect for vacations and sandal season.',
  },
  {
    id: 'nail-art-simple',
    category: 'nail-art',
    name: 'Nail Art - Simple',
    duration: 15,
    price: 100,
    description: 'Per nail. Simple designs, dots, stripes, or single accent nail.',
  },
  {
    id: 'nail-art-detailed',
    category: 'nail-art',
    name: 'Nail Art - Detailed',
    duration: 25,
    price: 200,
    description: 'Per nail. Intricate designs, florals, gems, or hand-painted art.',
  },
  {
    id: 'gel-removal',
    category: 'add-ons',
    name: 'Gel Removal',
    duration: 15,
    price: 300,
    description: 'Safe soak-off removal for gel polish.',
  },
  {
    id: 'nail-repair',
    category: 'add-ons',
    name: 'Nail Repair',
    duration: 10,
    price: 100,
    description: 'Per nail. Fix cracks or breaks with silk wrap.',
  },
  {
    id: 'paraffin-treatment',
    category: 'add-ons',
    name: 'Paraffin Treatment',
    duration: 15,
    price: 300,
    description: 'Deeply moisturizing warm wax treatment for hands or feet.',
  },
];